# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-30 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_auto_20221129_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.ManyToManyField(related_name='items', through='food_app.StoreItem', to='food_app.Store'),
        ),
    ]
