# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_auto_20221130_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b1d15538-87c5-497a-a6f7-5a37af9e6e98'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='food_app.Item'),
        ),
    ]
